ENV_UCC_POSTGRESQL: 10.217.182.161
ENV_UCC_POSTGRESQL_PORT: 5432
ENV_UCC_POSTGRESQL_DB: csaidev

ENV_CSAI_POSTGRESQL_SCHEMA: csai
POSTGRESQL_USERNAME: ENC(5XjG3R/s4u7Abm/TwSjkwr0pRCmguXKEO3RexYerX38=)
POSTGRESQL_PASSWORD: ENC(HhBycntGUedwXVSDfHcjvLz7L2pw4wOELgsWTJStW9szS5iOLjoMdA==)

PROXY_DOMAIN: https://dev.api.csai.kt.co.kr:8090

FILE:
  CHAT: /home/tomcat/data/chat/
  
URL:
  ALARM_TALK:
    SEND: ${PROXY_DOMAIN}/alarm/send
  CONSULT:
    SEND: 
      TEXT: ${PROXY_DOMAIN}/consult/send/text
      IMAGE-BASE64: ${PROXY_DOMAIN}/consult/send/image/base64
      IMAGE: ${PROXY_DOMAIN}/consult/send/image
      MESSAGE: ${PROXY_DOMAIN}/consult/send/message
      FILE: ${PROXY_DOMAIN}/consult/send/file   
  OSB: ENC(v0tTTvOm1dwGtSxMF7gpgGYH0/t3H6f7Y1c9lP9UVPburOiLlhHAdQ==)
  WEB: https://dev.csai.kt.co.kr:8080
    
LDAP:
  CONN:
    HOST: ENC(ZK221Fn0Eum9NRaFq4EAE1ZeSNhTC5mfCETyeb6ObLzZWf+KBfj1eaBjC4SzXKm2)
    SSLYN: true
    PORT: ENC(837Nu3KyQ0x/NnrfvGgq65591X5YbMAbHi44p1lwAXc=)
    BASEDN: OU=Employee,DC=ldap,DC=ktlab,DC=dev
    ID: ENC(tbgv7s/09QUCgqIp4HBRtawNGSNBEiktuHQWL8IkhqvcXPubPhSSgGUAR9vwGgDM)
    PWD: ENC(tHQmzmXOXBZv8Hqeu1ofCmXz68NVZu65RvXJy2/aQhNcKVsnuit87MrEvCpFUuc1)

server:
  port: 8080
  servlet:
    session:
      timeout: 1800

# spring default
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
  main:
    allow-bean-definition-overriding: true
  jwt:
    secret: ENC(Al9ZPDSDUi9sQAkNcnoD8RyXpcrnnGohayfVxPZhXuJSwRWcPP6NI3d+Ft+6wsweou6h0X2yIOqo5JwbaYhT6A==)
#  profiles:
#    active: local
# JPA POSTGRESQL 파티션  처리 / 바인딩 # $

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ENV_UCC_POSTGRESQL}:${ENV_UCC_POSTGRESQL_PORT}/${ENV_UCC_POSTGRESQL_DB}?autoReconnect=true&currentSchema=${ENV_CSAI_POSTGRESQL_SCHEMA}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}


  h2:
    console:
      enabled: true
      
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncrptor  